name: Release

on:
  push:
    tags:
      - '*'

# 添加权限配置
permissions:
  contents: write  # 这是创建release所必需的权限

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Get tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: |
          # 设置编译环境变量
          export CGO_ENABLED=0
          
          # 创建输出目录
          mkdir -p dist
          
          # 编译服务器版本
          echo "Building server version..."
          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-server_windows_amd64.exe ./cmd/server
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-server_linux_amd64 ./cmd/server
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-server_linux_arm64 ./cmd/server
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-server_darwin_amd64 ./cmd/server
          # macOS ARM64
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-server_darwin_arm64 ./cmd/server
          
          # 编译GitHub Action版本
          echo "Building GitHub Action version..."
          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-gh-action_windows_amd64.exe ./cmd/github-action
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-gh-action_linux_amd64 ./cmd/github-action
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-gh-action_linux_arm64 ./cmd/github-action
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-gh-action_darwin_amd64 ./cmd/github-action
          # macOS ARM64
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-gh-action_darwin_arm64 ./cmd/github-action
          
          # 编译Lambda版本
          echo "Building Lambda version..."
          # Linux AMD64 (Lambda通常只在Linux上运行)
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-lambda_linux_amd64 ./cmd/lambda
          # Linux ARM64 (支持ARM Lambda)
          GOOS=linux GOARCH=arm64 go build -ldflags="-X main.Version=${TAG} -s -w" -o dist/cr-bot-lambda_linux_arm64 ./cmd/lambda

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cr-bot-server_windows_amd64.exe
            dist/cr-bot-server_linux_amd64
            dist/cr-bot-server_linux_arm64
            dist/cr-bot-server_darwin_amd64
            dist/cr-bot-server_darwin_arm64
            dist/cr-bot-gh-action_windows_amd64.exe
            dist/cr-bot-gh-action_linux_amd64
            dist/cr-bot-gh-action_linux_arm64
            dist/cr-bot-gh-action_darwin_amd64
            dist/cr-bot-gh-action_darwin_arm64
            dist/cr-bot-lambda_linux_amd64
            dist/cr-bot-lambda_linux_arm64
            dist/SHA256SUMS.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
